---
title: "Analysis code VA"
output: html_document
author: "Vicente Arrona"
date: "05-02-2024" 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These are the anonymised datasets by country and the complete dataset

```{r import datasets}
ds <- readRDS("data/data_complete.rds")
ds_sp <- readRDS("data/data_Spain.rds")
ds_cr <- readRDS("data/data_Czech_Republic.rds")
ds_nl <- readRDS("data/data_Netherlands.rds")
ds_it <- readRDS("data/data_Italy.rds")


## Codebook for reference
cb <- 
  openxlsx::read.xlsx("ext/all_codebook.xlsx", sheet = 1)
```

```{r req packs}
library(tidyverse)
library(ggpubr) # arranges ggplots
library(visdat)
library(naniar)
library(knitr)
library(gtsummary)
library(skimr)
library(kableExtra) #Saves tables made with kable
library(patchwork) 
library(scales)
```

### Questionnaire scores

```{r questionnaire scores}
# Create objects with cut-off scores per country

phq_co_st <- c("CZ",
               "IT",
               "NL")

phq_co_12 <- c("ES")

gad_co_st <- c("CZ",
               "IT",
               "ES")

gad_co_12 <- "NL"


      if_all(ad34:ad45, ~ !is.na(.)) ~ "Complete GHQ"
      if_all(pcptsd1:pcptsd5, ~ !is.na(.)) ~ "Complete PC-PTSD-5"
      if_all(re57:re63, ~ !is.na(.)) ~ "Complete BRS"
      if_all(tea47:tea49, ~ !is.na(.)) ~ "Complete Trauma questions"


ds <- 
  ds |> 
  mutate(phq_sc = rowSums(
    across(
      contains("phq")), na.rm = TRUE),   # rowSums has to be the 1st verb
    phq_co = case_when(
      country_of_residence %in% phq_co_st & phq_sc >= 10 ~ "Yes",
      country_of_residence %in% phq_co_12 & phq_sc >= 12 ~ "Yes",
      TRUE ~ "No"),      
    phq_cat = case_when(
      phq_sc < 4 ~ "Minimal symptoms",
      phq_sc >= 4 & phq_sc < 10 ~ "Mild symptoms",
      phq_sc >= 10 & phq_sc < 14 ~ "Moderate symptoms",
      phq_sc >= 14 & phq_sc < 20 ~ "Moderately severe symptoms", 
      phq_sc >= 20 ~ "Severe symptoms"),
    phq_cat = as.ordered(phq_cat)
  )

ds <- 
  ds |> 
  mutate(gad_sc = rowSums(
    across(
      contains("gad")), na.rm = TRUE),
    gad_co = case_when(
      country_of_residence %in% gad_co_st & gad_sc >= 10 ~ "Yes",
      country_of_residence %in% gad_co_12 & gad_sc >= 12 ~ "Yes",
      TRUE ~ "No"),
    gad_cat = case_when(
      gad_sc < 4 ~ "Minimal symptoms",
      gad_sc >= 4 & gad_sc < 10 ~ "Mild symptoms",
      gad_sc >= 10 & gad_sc < 14 ~ "Moderate symptoms",
      gad_sc >= 14 & gad_sc < 20 ~ "Moderately severe symptoms", 
      gad_sc >= 20 ~ "Severe symptoms"),
    gad_cat = as.ordered(gad_cat)
  )

rm(gad_co_12, gad_co_st, phq_co_st, phq_co_12)
```

## Questionnaire completion

```{r questionnaire completion}
ds <- 
  ds |> 
  mutate(
    ghq_comp = case_when(
      if_all(ad34:ad45, ~ !is.na(.)) ~ "Complete GHQ",
      TRUE ~ "Incomplete GHQ"),
    gad_comp = case_when(
      if_all(gad1:gad7, ~ !is.na(.)) ~ "Complete GAD-7",
      TRUE ~ "Incomplete GAD-7"),
    pcptsd5_comp = case_when(
      if_all(pcptsd1:pcptsd5, ~ !is.na(.)) ~ "Complete PC-PTSD-5",
      TRUE ~ "Incomplete PC-PTSD-5"),
    phq_comp = case_when(
      if_all(phq68:phq76, ~ !is.na(.)) ~ "Complete PHQ-9",
      TRUE ~ "Incomplete PHQ-9"),
    brs_comp = case_when(
      if_all(re57:re63, ~ !is.na(.)) ~ "Complete BRS",
      TRUE ~ "Incomplete BRS"),
    trauma_comp = case_when(
      if_all(tea47:tea49, ~ !is.na(.)) ~ "Complete Trauma questions",
      TRUE ~ "Incomplete trauma questions"))

ds |> 
  select(wave,
         ghq_comp,
         gad_comp,
         pcptsd5_comp,
         phq_comp,
         brs_comp,
         trauma_comp,
         country_of_residence) |> 
  tbl_summary(by = country_of_residence)
```

### Healthcare worker density per 10,000 people.

```{r hcw density}
density_prof <- 
  readxl::read_xlsx("ext/hcw_per_10k.xlsx") |>   # Data 
  select(country, nurses_20, doctors_20) |> 
  mutate(country = case_when(
    country == "Czechia" ~ "CZ",
    country == "Italy" ~ "IT",
    country == "Netherlands" ~ "NL",
    country == "Spain" ~ "ES",
    TRUE ~ country)
    )

ds <- 
  ds |> 
  left_join(density_prof, 
            by = c("country_of_residence" = "country")) # Join data 

ds <- 
  ds |>
  mutate(nur_density_2020 = nurses_20,
         doc_density_2020 = doctors_20)

rm(density_prof)
```

```{r filter ids by participation in waves}
ds_1_2 <- 
  ds |> 
  filter(wave %in% c(1, 2)) |>  # Maintains waves of interest
  group_by(hashed_id) |> 
  filter(n_distinct(wave) == 2) |>  # Ensures id is in exactly those 2 waves.
  ungroup()

table(ds_1_2$wave, ds_1_2$country_of_residence) # Check

ds_1_3 <- 
  ds |> 
  filter(wave %in% c(1, 3)) |> 
  group_by(hashed_id) |> 
  filter(n_distinct(wave) == 2) |> 
  ungroup()

table(ds_1_3$wave, ds_1_3$country_of_residence)

ds_2_3 <- 
  ds |> 
  filter(wave %in% c(2, 3)) |> 
  group_by(hashed_id) |> 
  filter(n_distinct(wave) == 2) |> 
  ungroup()

table(ds_2_3$wave, ds_2_3$country_of_residence)

ds_all_waves <- 
  ds |> 
  group_by(hashed_id) |> 
  filter(n() == 3) |> 
  ungroup()

table(ds_all_waves$wave, ds_all_waves$country_of_residence)
```
